### PR TITLE
Added support for core-js@3

### PR DESCRIPTION
**Pull request by BenWT**

### CODE REVIEW

**Comment by nodkz** [comment]
@felippepuhle if you approve these changes then I'll merge it.

Thanks!

**Review by felippepuhle — APPROVED** [review]
I've been using react-relay-network-modern basically with RN, but I think we can merge it.

If we were really supporting IE 9 maybe we can add a note on the README file

**Comment by nodkz** [comment]
@BenWT @felippepuhle thanks for your contribution and help!

I think that we should not support IE9.

**Pull request merged**
