### PR TITLE
Catch more case in error parser

### PR DESCRIPTION
**Pull request by tranvansang**
Fix error parser's error when using persisted query

### CODE REVIEW

**Comment by nodkz** [comment]
Thanks a lot!

**Comment by felippepuhle** [comment]
this PR broke some tests

**Comment by nodkz** [comment]
What the hell? Why travis & github lost CI status... I accepted PR without seeing fallen tests. 🤬

@felippepuhle thanks for reporting 👍

@tranvansang can you fix broken tests in new PR? Tnx. 😉

**Comment by felippepuhle** [comment]
I don't know exactly what's happening, but I think we'll need to manually specify the operation for each test, [here](https://github.com/relay-tools/react-relay-network-modern/blob/master/src/__tests__/fetchWithMiddleware-test.js#L164) for example

**Comment by nodkz** [comment]
Fixed in https://github.com/relay-tools/react-relay-network-modern/commit/a9a036ff1a02f0be5e9fe9b667b1bf2ec6a2d2b8

**Comment by tranvansang** [comment]
> Fixed in [a9a036f](https://github.com/relay-tools/react-relay-network-modern/commit/a9a036ff1a02f0be5e9fe9b667b1bf2ec6a2d2b8)

Thank you very much!

**Pull request merged**
