### PR TITLE
[cacheMiddleware] Do not cache responses with errors

### PR DESCRIPTION
**Pull request by helielson**
Currently the cache middleware is caching any response, even it has a error.
This PR fix it.

### CODE REVIEW

**Comment by nodkz** [comment]
Thanks for this.

I agree that by default we should not cache errors.

Can I ask you to add an option `allowCacheErrors` or any other better name? We should provide a way to keep old behavior.

**Comment by helielson** [comment]
sure @nodkz. I'll do it

**Comment by helielson** [comment]
Done @nodkz.
A question: what should be the default behavior? Do not cache?

**Comment by nodkz** [comment]
Yep, by default do not cache. Exactly what your current code does.

Please add info about the new option to readme.md and I ready to merge and publish new package version.

**Comment by helielson** [comment]
README updated. 
I just noticed that the lib is using the `allow` prefix in some options.
Should I change it to `allowCacheErrors`?

**Comment by nodkz** [comment]
Let save our time and keep this option name as is. 😉

The package will be published after tests.
Thanks for improvement! 👍

**Comment by helielson** [comment]
Thank you for your quick review!

**Pull request merged**
