### PR TITLE
Batch request list as array & check duplicates comparing body

### PR DESCRIPTION
**Pull request by joelvh**
* Tracks batch requests in Array instead of Map #31
* Determines duplicate requests based on body of request (which includes the request ID) #31, #48

### CODE REVIEW

**Comment by nodkz** [comment]
Great Job! Thanks! 👍

To move further we should decide what to do next:

**Case 1**:
- Bump new 4.0.0 version (cause new batching may break someone's code)
- Add notes to README about changes (and provide info about legacyBatch)

**Case 2**:
- Bump v3.1.0 with changes in this PR
  - Return back batchMiddlware for backward compatibility
  - Create new `batch2Middleware` or something like

Both case a legit for me.

**Comment by joelvh** [comment]
My assumption is that the GraphQL server implementation would be returning results in order of the request. It’s hard to imagine an implementation that might rely on the request ID unless maybe threads are used for parallel processing possibly, which might produce a different order.

Our backend uses the Ruby implementation of a GraphQL library and there is no way to assign an ID to each result, so order is important. 

For those reasons, I would vote for Case 1. Note that I removed tests for the “legacy” version, so maybe they need to be added back. What I found while updating tests is that with an array and no request IDs to match and test matching, there are probably several tests that are redundant now too.

Lastly, there are several other Issues open related to batching. I would like to see if we can incorporate any of those in a 4.0 release and finally close them out?

**Comment by nodkz** [comment]
Agreed. Let's move to 4.0 release.

Can you add notes to README about changes (and provide info about legacyBatch)?

After that, I'm ready to bump 4.0.
Or even more if you have bandwidth to fix other issues - i'll wait to include them to 4.0.0, or we may ship them later.

Thanks.

**Comment by tomconroy** [comment]
This is a major blocker from me adopting this library – would love to see it released! ❤️

**Comment by joelvh** [comment]
@nodkz added the legacyBatch tests back and updated docs.

I reviewed the open batch-related issues and most seem  like they should be closed (e.g. #45, #15, #8, #7)

I only see addressing #67, but in a future release.

Let  me know if there's anything else holding up  the release. Thanks!

**Comment by nodkz** [comment]
Amazing PULL REQUEST 👍

Thanks a lot 🙏

**Pull request merged**
