### PR TITLE
feat: Add Persisted Queries middleware

### PR DESCRIPTION
**Pull request by limaAniceto**
Opening this as a follow-up of this issue:
https://github.com/relay-tools/react-relay-network-modern/issues/60

This is a shared contribution with Greg Collet (he's not here but might drop in if needed)

### CODE REVIEW

**Comment by nodkz** [comment]
@limaAniceto thanks for your contribution.

It will be nice if you add some docs to readme.md about this middleware in new PR.

**Comment by limaAniceto** [comment]
@nodkz no worries

Greg Collet and I did it together, one of us will make the docs PR for you in the coming days

Thanks a ton for reviewing/merging this 👍

**Comment by nodkz** [comment]
@santino thanks for pointing that. There were problems with Travis & lint. Should be fixed via https://github.com/relay-tools/react-relay-network-modern/commit/d4d3cdad05d727af74a73071231acb943ff17332

Now builds migrated to GitLab actions. And any further merges should publish a new package version automatically like before.

**Comment by santino** [comment]
Brilliant, thank you so much!

**Pull request merged**
