### PR TITLE
fix: handle network error in retry function and add a callback

### LINKED ISSUE #36: retryMiddleware does not retry on Network request failed error
What is the reasoning behind the check on 112 in `middlewares/retry.js`:

```javascript
if (e && e.res && o.retryOnStatusCode(e.res.status, o.req, e.res)) {
```

In a case where the request does not reach the server (network connection problem, etc.), this check fails and the error is rethrown instead of a making another retriable request. Have you considered handling such cases?

### PR DESCRIPTION
**Pull request by ntelkedzhiev**
Closes #36

### CODE REVIEW

**Comment by ntelkedzhiev** [comment]
@nodkz Should `forceRetry` and `onRetry` be combined in something like `onRetry(cb, delay, attempt)`? Also, do you want me to only handle the `Network request failed error` or all error that do not contain a response from the server.

**Comment by nodkz** [comment]
@ntelkedzhiev can you fix broken tests?
Also, run `yarn lint` it also throws indentation errors (`tab` -> `2 spaces`).

Run `yarn test` or `npm test` to run all tests locally before committing. 

> Should forceRetry and onRetry be combined in something like onRetry(forceRetry, delay, attempt)?

While reviewing your code I came with the same idea about improvement of `onRetry` method. 
Let's do it! 👍 
But add more functionality to it - `onRetry(meta: { forceRetry: Function, delay: number, attempt: number, lastError: Error }): false | any`:
- make one argument `meta`, with 4 properties (it allows to add more props in future without care of its order)
- if this method returns `false` then abort requests, otherwise for any other returned value (even `null`, `undefined`) middleware should continue requests.

`forceRetry` is unobvious and looks like some piece of 💩 BUT `forceRetry` needs to leave as is for backward compatibility and mark as DEPRECATED in readme.md.

> Also, do you want me to only handle the Network request failed error or all error that do not contain a response from the server as it is now.

For now, I don't know what behavior will be better. So do it according to your real use cases.

**Comment by ntelkedzhiev** [comment]
Sounds good! Thanks for the suggestions! Will do.

**Comment by ntelkedzhiev** [comment]
@nodkz When I run `yarn test` I get 
```
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```
Any idea why?

**Comment by ntelkedzhiev** [comment]
I'm not getting:

```
 Jest encountered an unexpected token
  ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){
import fetchMock from 'fetch-mock';
^^^^^^
SyntaxError: Unexpected token import
```

**Comment by nodkz** [comment]
I have just clone your repo, and all works good on MacOS:

```bash
git clone git@github.com:ntelkedzhiev/react-relay-network-modern.git ./_fork_rrnm

yarn install 
# it returns some warnings with `fsevents`, but just ommit them

yarn test
# returns following output
```

screen shot 2018-09-17 at 19 40 55

**What operation system do you use?**

**Comment by nodkz** [comment]
What operation system do you use?

---

Your error looks like that `babel` was resolved incorrectly by `node`.

Maybe you have globally installed `babel`? 
Try to remove it
```
npm uninstall -g babel
npm uninstall -g babel-cli
npm uninstall -g jest
```

**Comment by ntelkedzhiev** [comment]
Very weird. I tried it on two Macs. Running `node` 9.11.2 and 10.10.0. Not sure how to fix that.

**Comment by nodkz** [comment]
What yarn version do you use?
``` 
yarn --version
```
Mine is `1.7.0`

Just updated to the latest version `1.9.4`
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```
And try again it with your repo to run tests. And it works without `babel` error.

**Comment by nodkz** [comment]
If you update `yarn`, you need to remove `node_modules` folder and install packages again via `yarn install`.

**Comment by ntelkedzhiev** [comment]
I'm running 1.9.4 as well.

**Comment by ntelkedzhiev** [comment]
Maybe this is needed: https://github.com/facebook/jest/issues/6053#issuecomment-383632515.

**Comment by nodkz** [comment]
Damn. First time met such problem.

Can you confirm that parent folders do not contain `.babelrc` files? 
Maybe they somehow overrides settings from `.babelrc` in this repo?!

**Comment by ntelkedzhiev** [comment]
Yes, no `.babelrc` files in parent folders.

**Comment by nodkz** [comment]
Just updated packages in `master`, can you merge this changes to your repo. 

Tried to do it directly to your repo, but it looks like that you do not allow (remove checkbox when open PR) to send commits from maintainers/contributors.

After merging with master, it required to run `yarn install` for updating packages. Maybe it solves a problem, maybe not.

**Comment by ntelkedzhiev** [comment]
@nodkz Didn't have success after you pushed the changes. I added `babel.config.js` file (and removed `.babelrc`) as documented here: https://github.com/facebook/jest/blob/master/docs/GettingStarted.md#using-babel. 

-----

Also fixed the error, so PR is ready to merge. Let me know what you want to do with the `babel` issue and whether you want me to make any further changes.

**Comment by nodkz** [comment]
Please return back all babel configs, they are required for package building for the different environments.

Just copy all content from https://github.com/relay-tools/react-relay-network-modern/blob/master/.babelrc to `babel.config.js`.

**Comment by nodkz** [comment]
This code has some bug in tests.

When running tests in watch mode:
```
yarn watch
```
and re-run tests several times, it sometimes throws an error, sometimes pass.

It's a very strange behavior. Try to review it tomorrow.

**Comment by ntelkedzhiev** [comment]
Agreed. It needs to be rewritten.

**Comment by nodkz** [comment]
@ntelkedzhiev Done. Please test it with your app.

NOTABLE CHANGE: Property `onRetry` was renamed to `beforeRetry`. It's a better name because it allows to abort following retry or run it immediately.

1. Pull latest changes from `ntelkedzhiev/react-relay-network-modern`
2. Run
```
yarn build
```
3. Copy generated `lib`, `es`, `mjs`, `node8` folders to your app's `node_modules/react-relay-network-modern` folder.
4. Launch your app

**Comment by nodkz** [comment]
My coworkers tested the new version with their app. All works well.
So you may try the published version from npm and if you find an error, please let me know.

Thanks for your help!

**Comment by ntelkedzhiev** [comment]
@nodkz Great! Thanks a lot man!

**Pull request merged**
